AvaAulas/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('inicio/', include('plataforma.urls')),
    path('aulas/', include('plataforma.urls')),
    path('resultados/', include('resultados.urls')),
    path('', include('usuarios.urls')),
    path('', include('plataforma.urls'))
]

plataforma/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.aulas, name = 'aulas')
]

resultados/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.result, name = 'result')
]

usuarios/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/',views.cadastro, name ='cadastro'),
    path('login/',views.login, name ='login'),
    path('sair/', views.sair, name='sair'),
    path('', views.plataforma, name='plataforma'),
]

plataforma/models.py
from django.db import models

# Create your models here.

resultados/models.py
from django.db import models

# Create your models here.

usuarios/models.py
import datetime
from django.db import models

from django.utils import timezone


class NivelCurso(models.Model):
    descricao = models.CharField(max_length=50)

    def __str__(self):
        return self.desc_nivel


class Curso(models.Model):
    nome = models.CharField(max_length=100)
    ativo = models.BooleanField
    nivel = models.ForeignKey(
        "NivelCurso", on_delete=models.RESTRICT, related_name="cursos"
    )

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length=100)
    carga_horaria = models.IntegerField
    ano_letivo = models.IntegerField
    semestral = models.BooleanField()

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if (self.semestral) and (self.semestre == None):
            self.semestre = 1
        super(Disciplina, self).save(*args, **kwargs)


class Area(models.Model):
    nome = models.CharField(max_length=80)


class Professor(models.Model):
    nome = models.CharField(max_length=150)
    area = models.ForeignKey(
        "Area", on_delete=models.RESTRICT, related_name="professores"
    )

    def __str__(self):
        return self.nome


class Oferta(models.Model):
    class SemestreLetivo(models.IntegerChoices):
        PRIMEIRO = 1, "1º Semestre"
        SEGUNDO = 2, "2º Semestre"

    ano = models.IntegerField
    professor = models.ForeignKey(
        "Professor", on_delete=models.RESTRICT, related_name="disciplinas"
    )
    disciplina = models.ForeignKey(
        "Disciplina", on_delete=models.RESTRICT, related_name="professores"
    )
    semestre = models.IntegerField(
        choices=SemestreLetivo.choices,
        default=SemestreLetivo.PRIMEIRO,
        blank=True,
        null=True,
    )
    turma = models.CharField

    def __str__(self) -> str:
        return self.professor


class Formulario(models.Model):
    disciplina = models.ForeignKey("Disciplina", on_delete=models.RESTRICT)
    data_aula = models.DateField
    tema_aula = models.CharField(max_length=100)
    descricao_aula = models.CharField(max_length=500)
    data_limite_resposta = models.DateField

    def __str__(self):
        return self.tema_aula


class Pergunta(models.Model):
    TIPO_CHOICES = ("O", "Objetiva")("D", "Discursiva")
    pergunta_texto = models.CharField(max_length=200)
    formulario = models.ForeignKey("Formulario", on_delete=models.RESTRICT)
    tipo_pergunta = models.CharField(choices=TIPO_CHOICES, blank=False, null=False)

    class Meta:
        verbose_name_plural = "Perguntas"

    def __str__(self):
        return self.pergunta_texto


class Opcao(models.Model):
    class Meta:
        verbose_name_plural = "Opções"

    pergunta = models.ForeignKey(Pergunta, on_delete=models.RESTRICT)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_texto


class Resposta(models.Model):
    pergunta = models.ForeignKey("Pergunta", on_delete=models.RESTRICT)
    resposta = models.ForeignKey("Opcao", on_delete=models.RESTRICT)
    data_hora = models.DateTimeField

    def __str__(self):
        return self.resposta

plataforma/views.py
from django.shortcuts import render
from calendar import c
import email
from http.client import HTTPResponse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

def plataforma(request):
     return render(request, 'index.html')

@login_required(login_url="/auth/login/")
def aulas(request):
    return render(request, 'aulas.html')

resultados/views.py
from django.shortcuts import render
from calendar import c
import email
from http.client import HTTPResponse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

@login_required(login_url="/auth/login/")
def result(request):
     return render(request, 'result.html')

usuarios/views.py
# Importações login
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from telnetlib import STATUS
# Importações importantes do django
from django.shortcuts import redirect, render,  get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Aleatorias
from django.utils import timezone

# Funções de login
def cadastro(request):
    status = request.GET.get('status')
    if request.method == "GET":
        return render(request, 'cadastro.html', {'status': status})

    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user = User.objects.filter(username=username).first()

    if len(senha) < 6:
        return redirect('/auth/cadastro/?status=1')

    if len(username) < 3:
        return redirect('/auth/cadastro/?status=2')

    if user:
        return redirect('/auth/cadastro/?status=3')

    user = User.objects.create_user(
        username=username, email=email, password=senha)
    user.save()

    return redirect('/auth/login/?status=0')


def login(request):
    status = request.GET.get('status')
    if request.method == "GET":
        return render(request, 'login.html', {'status': status})
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(username=username, password=senha)

        if user:
            login_django(request, user)
            return render(request, 'index.html')
        else:
            return redirect('/auth/login/?status=4')


def sair(request):
    logout(request)
    return HttpResponseRedirect('/auth/login')

# Funções das telas
def plataforma(request):
    return render(request, 'index.html')

usuarios/templates/aulas.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/nav.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Aulas - AvaAulas</title>
    
</head>
<body> 
    <header>
        <nav>
          <a class="textoNav2" href="index">A//V</a>
          <a class="logo" href="/inicio">AvaAulas</a>
          <div class="mobile-menu">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>
          <ul class="nav-list">
            <li><a class="textoNav" href="/">Início</a></li>
            <li><a class="textoNav" href="/aulas/">Aulas</a></li>
            <li><a class="textoNav" href="/resultados/">Resultados</a></li>
            <li><a class="textoNav" href="/auth/sair">Logout</a></li>
          </ul>
        </nav>
      </header>
    <div class="centro">
        <h1>Ultimas Aulas</h1>
    </div>
    <script src="{% static 'js/index.js'%}"></script>
  
</body>
</html>

usuarios/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Cadastro - AvaAulas</title>
</head>
<body>
    {% if status == '1'%}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Erro!</strong> A senha deve ter pelo menos 6 caracteres.
    </div>
    {%endif%}
    {% if status == '2'%}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Erro!</strong> o usuario deve ter pelo menos 3 caracteres.
    </div>
    {%endif%}
    {% if status == '3'%}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Erro!</strong> Usuário já existe.
    </div>
    {%endif%}
    {% if status == '4'%}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Erro!</strong> Nome ou senha invalidos.
    </div>
    {%endif%}
    {% if status == '0'%}
    <div class="alertBom">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Sucesso!</strong> Cadastro realizado com sucesso.
    </div>
    {%endif%}
    <main class="container">
<h2>Cadastrar</h2>
<form action = "{%url 'cadastro'%}" method = "POST"> {%csrf_token%} 
    <div class="input-field">
        <input type="text" placeholder="Seu nome" name="username">
        <div class="underline"></div>
    </div>
    <div class="input-field">
        <input type="email" placeholder="Seu Email" name="email">
        <div class="underline"></div>
    </div>
    <div class="input-field">
        <input type="password" placeholder="Sua senha" name="senha">
    <div class="underline"></div>
</div>
    <input type="submit" value="cadastrar">
    <p>Já tem um usuario? <a href="{%url 'login'%}">Logar!</a></p>
    <br>
</form>
    </main>
    
   
</body>
</html>

usuarios/templates/detalhe.html
<h1>{{ pergunta.pergunta_texto }}</h1>

{% if error_message %}<strong><h3 style="color:red;">{{ error_message }}</h3></strong>{% endif %}

<form action="{% url 'voto' pergunta.id %}" method="post">
{% csrf_token %}
{% for opcao in pergunta.opcao_set.all %}
    <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
    <label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto }}</label><br>
{% endfor %}
<br/>
<input type="submit" value="Votar">
</form>

usuarios/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/nav.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Inicio - AvaAulas</title>
    
</head>
<body> 
    <header>
        <nav>
          <a class="textoNav2" href="index">A//V</a>
          <a class="logo" href="/inicio">AvaAulas</a>
          <div class="mobile-menu">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>
          <ul class="nav-list">
            <li><a class="textoNav" href="/">Início</a></li>
            <li><a class="textoNav" href="/aulas/">Aulas</a></li>
            <li><a class="textoNav" href="/resultados/">Resultados</a></li>
            <li><a class="textoNav" href="/auth/sair">Logout</a></li>
          </ul>
        </nav>
      </header>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

      <h1> Responda o questionário </h1>
      {% if lista_ultimas_perguntas %}
          <ul>
          {% for pergunta in lista_ultimas_perguntas %}
              <li><a href="{% url 'templates: detalhe' pergunta.id %}">{{ pergunta.pergunta_texto }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p>Não há aulas para avaliar disponíveis.</p>
      {% endif %}
    <script src="{% static 'js/index.js'%}"></script>
  
</body>
</html>

usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
    <title>Login - AvaAulas</title>
</head>
<body>
    {% if status == '4'%}
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Erro!</strong> Nome ou senha invalidos.
    </div>
    {%endif%}
    {% if status == '0'%}
    <div class="alertBom">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Sucesso!</strong> Cadastro realizado com sucesso.
    </div>
    {%endif%}
    <main class="container">
        <h2>Login</h2>

        <form action = "{%url 'login'%}" method = "POST"> 
            {% csrf_token %} 
            <div class="input-field">
                <input type="text" name="username" placeholder="Seu usuarío">
                <div class="underline"></div>
            </div>
            <br>
            <div class="input-field">
                <input type="password" name="senha" placeholder="Sua senha">
                <div class="underline"></div>
            </div>
            <input type="submit" value="Logar">
            <p>Não está cadastrado? <a href="{%url 'cadastro'%}">Cadastre-se!</a></p>
            <br>
        </form>
    
       
    </main>

   
</body>
</html>

usuarios/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/nav.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Resultados - AvaAulas</title>
    
</head>
<body> 
    <header>
        <nav>
          <a class="textoNav2" href="index">A//V</a>
          <a class="logo" href="/inicio">AvaAulas</a>
          <div class="mobile-menu">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>
          <ul class="nav-list">
            <li><a class="textoNav" href="/">Início</a></li>
            <li><a class="textoNav" href="/aulas/">Aulas</a></li>
            <li><a class="textoNav" href="/resultados/">Resultados</a></li>
            <li><a class="textoNav" href="/auth/sair">Logout</a></li>
          </ul>
        </nav>
      </header>
      <h1>aaaa</h1>

      <ul>
      {% for opcao in pergunta.opcao_set.all %}
          <li>{{ opcao.opcao_texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}</li>
      {% endfor %}
      </ul>
      
      <a href="{% url 'index' %}">Votar Novamente?</a>
    <script src="{% static 'js/index.js'%}"></script>
  
</body>
</html>